import { imp } from "ts-poet";

export const imports = {
  BlankNode: imp("BlankNode@@rdfjs/types"),
  dataFactory: imp("DataFactory:dataFactory@n3"),
  DatasetCore: imp("DatasetCore@@rdfjs/types"),
  DatasetFactory: imp("StoreFactory:DatasetFactory@n3"),
  Either: imp("Either@purify-ts"),
  EitherAsync: imp("EitherAsync@purify-ts"),
  GraphQLBoolean: imp("GraphQLBoolean@graphql"),
  GraphQLDate: imp("Date:GraphQLDate@graphql-scalars"),
  GraphQLDateTime: imp("DateTime:GraphQLDateTime@graphql-scalars"),
  GraphQLFloat: imp("GraphQLFloat@graphql"),
  GraphQLID: imp("GraphQLID@graphql"),
  GraphQLInt: imp("GraphQLInt@graphql"),
  GraphQLList: imp("GraphQLList@graphql"),
  GraphQLNonNull: imp("GraphQLNonNull@graphql"),
  GraphQLObjectType: imp("GraphQLObjectType@graphql"),
  GraphQLSchema: imp("GraphQLSchema@graphql"),
  GraphQLString: imp("GraphQLString@graphql"),
  GraphQLUnionType: imp("GraphQLUnionType@graphql"),
  Left: imp("Left@purify-ts"),
  Literal: imp("Literal@@rdfjs/types"),
  Maybe: imp("Maybe@purify-ts"),
  MutableResource: imp("MutableResource@rdfjs-resource"),
  MutableResourceSet: imp("MutableResourceSet@rdfjs-resource"),
  NamedNode: imp("NamedNode@@rdfjs/types"),
  NonEmptyList: imp("NonEmptyList@purify-ts"),
  Resource: imp("Resource@rdfjs-resource"),
  ResourceSet: imp("ResourceSet@rdfjs-resource"),
  sha256: imp("sha256@js-sha256"),
  sparqljs: imp("sparqljs*sparqljs"),
  uuid: imp("uuid*uuid"),
  Variable: imp("Variable@@rdfjs/types"),
  z: imp("z@zod"),
} as const;
