import { imp } from "./ts-poet-wrapper.js";

export const imports = {
  BigDecimal: imp("Decimal:BigDecimal@decimal.js"),
  BlankNode: imp("BlankNode@@rdfjs/types"),
  dataFactory: imp("dataFactory=@rdfjs/data-model"),
  DatasetCore: imp("DatasetCore@@rdfjs/types"),
  datasetFactory: imp("datasetFactory=@rdfjs/dataset"),
  Either: imp("Either@purify-ts"),
  EitherAsync: imp("EitherAsync@purify-ts"),
  GraphQLBigInt: imp("BigInt:GraphQLBigInt@graphql-scalars"),
  GraphQLBoolean: imp("GraphQLBoolean@graphql"),
  GraphQLDate: imp("Date:GraphQLDate@graphql-scalars"),
  GraphQLDateTime: imp("DateTime:GraphQLDateTime@graphql-scalars"),
  GraphQLFloat: imp("GraphQLFloat@graphql"),
  GraphQLID: imp("GraphQLID@graphql"),
  GraphQLInt: imp("GraphQLInt@graphql"),
  GraphQLList: imp("GraphQLList@graphql"),
  GraphQLNonNull: imp("GraphQLNonNull@graphql"),
  GraphQLObjectType: imp("GraphQLObjectType@graphql"),
  GraphQLSchema: imp("GraphQLSchema@graphql"),
  GraphQLString: imp("GraphQLString@graphql"),
  GraphQLUnionType: imp("GraphQLUnionType@graphql"),
  Left: imp("Left@purify-ts"),
  Literal: imp("Literal@@rdfjs/types"),
  LiteralFactory: imp("LiteralFactory@@rdfx/literal"),
  Maybe: imp("Maybe@purify-ts"),
  NamedNode: imp("NamedNode@@rdfjs/types"),
  NonEmptyList: imp("NonEmptyList@purify-ts"),
  Quad: imp("Quad@@rdfjs/types"),
  Quad_Graph: imp("Quad_Graph@@rdfjs/types"),
  RdfjsResourcePropertyPath: imp(
    "PropertyPath:RdfjsResourcePropertyPath@@rdfx/resource",
  ),
  Resource: imp("Resource@@rdfx/resource"),
  ResourceSet: imp("ResourceSet@@rdfx/resource"),
  Right: imp("Right@purify-ts"),
  sha256: imp("sha256@js-sha256"),
  sparqljs: imp("sparqljs*sparqljs"),
  uuid: imp("uuid*uuid"),
  Variable: imp("Variable@@rdfjs/types"),
  z: imp("z@zod"),
} as const;
