import { imp } from "ts-poet";

export const sharedImports = {
  BlankNode: imp("BlankNode@@rdfjs/types"),
  dataFactory: imp("DataFactory:dataFactory@n3"),
  DatasetFactory: imp("StoreFactory:DatasetFactory@n3"),
  Either: imp("Either@purify-ts"),
  GraphQLBoolean: imp("GraphQLBoolean@graphql"),
  GraphQLDate: imp("Date:GraphQLDate@graphql-scalars"),
  GraphQLDateTime: imp("DateTime:GraphQLDateTime@graphql-scalars"),
  GraphQLFloat: imp("GraphQLFloat@graphql"),
  GraphQLInt: imp("GraphQLInt@graphql"),
  GraphQLList: imp("GraphQLList@graphql"),
  GraphQLString: imp("GraphQLString@graphql"),
  Left: imp("Left@purify-ts"),
  Literal: imp("Literal@@rdfjs/types"),
  Maybe: imp("Maybe@purify-ts"),
  MutableResource: imp("MutableResource@rdfjs-resource"),
  MutableResourceSet: imp("MutableResourceSet@rdfjs-resource"),
  NamedNode: imp("NamedNode@@rdfjs/types"),
  NonEmptyList: imp("NonEmptyList@purify-ts"),
  Resource: imp("Resource@rdfjs-resource"),
  sha256: imp("sha256@js-sha256"),
  sparqljs: imp("sparqljs*@sparqljs"),
  uuid: imp("uuid*@uuid"),
  Variable: imp("Variable@@rdfjs/types"),
  z: imp("z@zod"),
} as const;
