export type TsFeature = (typeof TS_FEATURES)[number];

export const TS_FEATURES = [
  "GraphQL",
  "Object.create",
  "Object.equals",
  "Object.filter",
  "Object.fromJson",
  "Object.fromRdf",
  "Object.hash",
  "Object.JSON",
  "Object.JSON.type",
  "Object.JSON.parse",
  "Object.JSON.schema",
  "Object.JSON.uiSchema",
  "Object.RDF",
  "Object.schema",
  "Object.SPARQL",
  "Object.toJson",
  "Object.toRdf",
  "Object.toString",
  "Object.type",
  "ObjectSet",
  "RDF",
  "RdfjsDatasetObjectSet",
  "SPARQL",
  "SparqlObjectSet",
] as const;
