name: Continuous Integration
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch: null
jobs:
  build:
    env:
      DO_NOT_TRACK: 1
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test:coverage
      - name: Coverage report
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-path: coverage/coverage-summary.json
          json-final-path: coverage/coverage-final.json
      - name: Run CLI
        run: apps/cli/dist/cli.js generate ts
          examples/kitchen-sink/src/kitchen-sink.shaclmate.ttl >/dev/null
